//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FileSystemMessage : GeneralMessage
{
	private string changes
	{
		get;
		set;
	}

	private DateTime date
	{
		get;
		set;
	}

	private string sender
	{
		get;
		set;
	}

	public virtual string getString()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool setMessage(string message)
	{
		throw new System.NotImplementedException();
	}

}

