//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;


//General Failure Messages.
[DataContract]
public enum FailureType
{
    [EnumMember]
    FailedUserNotInBunch,
    [EnumMember]
	FailedUserDoesNotExist,
    [EnumMember]
    Good,
    [EnumMember]
    FailedUnknownReason,
    [EnumMember]
    FailedTargetUserDoesNotExist,
    [EnumMember]
    FailedUserNotAdmin,
    [EnumMember]
    FailedInvalidInput,
    [EnumMember]
    FailedUserAlreadyExist,
    [EnumMember]
    FailedConnectingFailed,
    [EnumMember]
    FailedBunchDoesNotExist,
    [EnumMember]
    FailedBadPassword,
    [EnumMember]
    FailedNotEqual,
    [EnumMember]
    FailedFileNotFound,
    [EnumMember]
    FailedLockNotRelease,
    [EnumMember]
    FailedInvalidUser,
    [EnumMember]
    FailedUserAlreadyOnline

}

//Actions that can be done in certain methods.
[DataContract]
public enum actions
{
    [EnumMember]
    Confirm,
    [EnumMember]
    Delete,
    [EnumMember]
    Create,
    [EnumMember]
    Move
}
