//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//This is not set to compile
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BunchoFiles : IBunchoFiles
{
    public const int MAX_TEXT = 100;

	public string name
	{
		get;
		set;
	}

    public int ID
	{
		get;
		set;
	}

    public int textCount
	{
		get;
		set;
	}

    //public virtual UserCollection Users
    //{
    //    get;
    //    set;
    //}

    public virtual Users Owner
	{
		get;
		set;
	}

    //public virtual UserCollection unconfirmedUsers
    //{
    //    get;
    //    set;
    //}

    public virtual string[] TextMessage
	{
		get;
		set;
	}

    public BunchoFiles()
    {
    }

    public virtual Queue<char> DCgetChanges()
    {
        throw new System.NotImplementedException();
    }

    public virtual remoteReturn DCsendChanges(Queue<char> sentChanges)
    {
        throw new System.NotImplementedException(); 
    }

	public virtual remoteReturn FGmodifyFile(actions option, Users myUser, string sourceLocation, string targetLocation)
	{
		throw new System.NotImplementedException();
	}

	public virtual remoteReturn FGmodifyUser(actions option, Users myUser, string targetUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual string[] FIgetList()
	{
		throw new System.NotImplementedException();
	}

	public virtual remoteReturn FIgetFile(Users myUser, string targetFile)
	{
		throw new System.NotImplementedException();
	}

}

