//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.ServiceModel;

[ServiceContract]
public interface IBunchoFiles 
{
    [OperationContract]
    Queue<char> DCgetChanges();

    [OperationContract]
    remoteReturn DCsendChanges(Queue<char> sentChanges);
    [OperationContract]
    remoteReturn FGmodifyFile(actions option, Users myUser, string sourceLocation, string targetLocation);
    [OperationContract]
    remoteReturn FGmodifyUser(actions option, Users myUser, string targetUser);
    [OperationContract]
	string[] FIgetList();
    [OperationContract]
    remoteReturn FIgetFile(Users myUser, string targetFile);

}

